import PlaceholderPage from "./PlaceholderPage";
import { TrendingUp } from "lucide-react";

export default function Analytics() {
  return (
    <PlaceholderPage
      title="Learning Analytics"
      description="Deep dive into your learning patterns with advanced analytics. Discover distraction trends, focus duration patterns, app usage insights, and weekly reflection reports generated by AI."
      icon={
        <TrendingUp className="w-10 h-10 text-purple-600 dark:text-purple-400" />
      }
    />
  );
}
